table _Medidas
	lineageTag: b5f8d3e2-94a6-4cab-ae17-8e4d2a39c156

	measure 'Valor Total' = SUM ( 'licitacoes_2019_2024'[valor] )
		formatString: R$ #,##0.00
		displayFolder: 01 Valores Base
		lineageTag: a1000001-0000-0000-0000-000000000001

	measure 'Qtd Itens' = SUM ( 'licitacoes_2019_2024'[quantidade] )
		formatString: #,##0
		displayFolder: 01 Valores Base
		lineageTag: a1000001-0000-0000-0000-000000000002

	measure 'Qtd Licitacoes' = DISTINCTCOUNT ( 'licitacoes_2019_2024'[id] )
		formatString: #,##0
		displayFolder: 01 Valores Base
		lineageTag: a1000001-0000-0000-0000-000000000003

	measure 'Qtd Fornecedores' = DISTINCTCOUNT ( 'licitacoes_2019_2024'[cpfCnpjVencedor] )
		formatString: #,##0
		displayFolder: 01 Valores Base
		lineageTag: a1000001-0000-0000-0000-000000000004

	measure 'Qtd Categorias' = DISTINCTCOUNT ( 'licitacoes_2019_2024'[categoria_ia] )
		formatString: #,##0
		displayFolder: 01 Valores Base
		lineageTag: a1000001-0000-0000-0000-000000000005

	measure 'Qtd Linhas' = COUNTROWS ( 'licitacoes_2019_2024' )
		formatString: #,##0
		displayFolder: 01 Valores Base
		lineageTag: a1000001-0000-0000-0000-000000000006

	measure 'Ticket Medio Licitacao' = DIVIDE ( [Valor Total], [Qtd Licitacoes] )
		formatString: R$ #,##0.00
		displayFolder: 02 Medias e Ticket
		lineageTag: a1000001-0000-0000-0000-000000000007

	measure 'Valor Medio Item' = DIVIDE ( [Valor Total], [Qtd Itens] )
		formatString: R$ #,##0.00
		displayFolder: 02 Medias e Ticket
		lineageTag: a1000001-0000-0000-0000-000000000008

	measure 'Valor Mediano Item' = MEDIAN ( 'licitacoes_2019_2024'[valor] )
		formatString: R$ #,##0.00
		displayFolder: 02 Medias e Ticket
		lineageTag: a1000001-0000-0000-0000-000000000009

	measure 'Itens por Licitacao' = DIVIDE ( [Qtd Itens], [Qtd Licitacoes] )
		formatString: #,##0.0
		displayFolder: 02 Medias e Ticket
		lineageTag: a1000001-0000-0000-0000-000000000010

	measure 'Valor Ano Anterior' = CALCULATE ( [Valor Total], SAMEPERIODLASTYEAR ( Calendario[Date] ) )
		formatString: R$ #,##0.00
		displayFolder: 03 Time Intelligence
		lineageTag: a1000001-0000-0000-0000-000000000011

	measure 'Valor Delta YoY' = [Valor Total] - [Valor Ano Anterior]
		formatString: R$ #,##0.00
		displayFolder: 03 Time Intelligence
		lineageTag: a1000001-0000-0000-0000-000000000012

	measure 'Valor YoY %' = DIVIDE ( [Valor Delta YoY], [Valor Ano Anterior] )
		formatString: 0.0%
		displayFolder: 03 Time Intelligence
		lineageTag: a1000001-0000-0000-0000-000000000013

	measure 'Valor Mes Anterior' = CALCULATE ( [Valor Total], DATEADD ( Calendario[Date], -1, MONTH ) )
		formatString: R$ #,##0.00
		displayFolder: 03 Time Intelligence
		lineageTag: a1000001-0000-0000-0000-000000000014

	measure 'Valor Delta MoM' = [Valor Total] - [Valor Mes Anterior]
		formatString: R$ #,##0.00
		displayFolder: 03 Time Intelligence
		lineageTag: a1000001-0000-0000-0000-000000000015

	measure 'Valor MoM %' = DIVIDE ( [Valor Delta MoM], [Valor Mes Anterior] )
		formatString: 0.0%
		displayFolder: 03 Time Intelligence
		lineageTag: a1000001-0000-0000-0000-000000000016

	measure 'Valor YTD' = TOTALYTD ( [Valor Total], Calendario[Date] )
		formatString: R$ #,##0.00
		displayFolder: 03 Time Intelligence
		lineageTag: a1000001-0000-0000-0000-000000000017

	measure 'Valor YTD Ano Anterior' = CALCULATE ( [Valor YTD], SAMEPERIODLASTYEAR ( Calendario[Date] ) )
		formatString: R$ #,##0.00
		displayFolder: 03 Time Intelligence
		lineageTag: a1000001-0000-0000-0000-000000000018

	measure 'Valor 12M Moveis' = CALCULATE ( [Valor Total], DATESINPERIOD ( Calendario[Date], LASTDATE ( Calendario[Date] ), -12, MONTH ) )
		formatString: R$ #,##0.00
		displayFolder: 03 Time Intelligence
		lineageTag: a1000001-0000-0000-0000-000000000019

	measure '% do Total Geral' = DIVIDE ( [Valor Total], CALCULATE ( [Valor Total], ALL ( 'licitacoes_2019_2024' ) ) )
		formatString: 0.0%
		displayFolder: 04 Participacao
		lineageTag: a1000001-0000-0000-0000-000000000020

	measure '% da Categoria' = DIVIDE ( [Valor Total], CALCULATE ( [Valor Total], ALLEXCEPT ( 'licitacoes_2019_2024', 'licitacoes_2019_2024'[categoria_ia] ) ) )
		formatString: 0.0%
		displayFolder: 04 Participacao
		lineageTag: a1000001-0000-0000-0000-000000000021

	measure '% do Ano' = DIVIDE ( [Valor Total], CALCULATE ( [Valor Total], ALLEXCEPT ( Calendario, Calendario[Ano] ) ) )
		formatString: 0.0%
		displayFolder: 04 Participacao
		lineageTag: a1000001-0000-0000-0000-000000000022

	measure 'Rank Categoria' = IF ( HASONEVALUE ( 'licitacoes_2019_2024'[categoria_ia] ), RANKX ( ALL ( 'licitacoes_2019_2024'[categoria_ia] ), [Valor Total],, DESC, DENSE ) )
		formatString: #,##0
		displayFolder: 05 Rankings
		lineageTag: a1000001-0000-0000-0000-000000000023

	measure 'Rank Fornecedor' = IF ( HASONEVALUE ( 'licitacoes_2019_2024'[nome] ), RANKX ( ALLSELECTED ( 'licitacoes_2019_2024'[nome], 'licitacoes_2019_2024'[cpfCnpjVencedor] ), [Valor Total],, DESC, DENSE ) )
		formatString: #,##0
		displayFolder: 05 Rankings
		lineageTag: a1000001-0000-0000-0000-000000000024

	measure 'Fornecedor #1 Nome' = CALCULATE ( SELECTEDVALUE ( 'licitacoes_2019_2024'[nome] ), TOPN ( 1, VALUES ( 'licitacoes_2019_2024'[nome] ), [Valor Total], DESC ) )
		displayFolder: 05 Rankings
		lineageTag: a1000001-0000-0000-0000-000000000025

	measure 'Fornecedor #1 Valor' = MAXX ( TOPN ( 1, VALUES ( 'licitacoes_2019_2024'[nome] ), [Valor Total], DESC ), [Valor Total] )
		formatString: R$ #,##0.00
		displayFolder: 05 Rankings
		lineageTag: a1000001-0000-0000-0000-000000000026

	measure 'Categoria #1 Nome' = CALCULATE ( SELECTEDVALUE ( 'licitacoes_2019_2024'[categoria_ia] ), TOPN ( 1, VALUES ( 'licitacoes_2019_2024'[categoria_ia] ), [Valor Total], DESC ) )
		displayFolder: 05 Rankings
		lineageTag: a1000001-0000-0000-0000-000000000027

	measure 'Valor Top 5 Fornecedores' =
			VAR Top5 = TOPN ( 5, VALUES ( 'licitacoes_2019_2024'[cpfCnpjVencedor] ), [Valor Total], DESC )
			RETURN CALCULATE ( [Valor Total], Top5 )
		formatString: R$ #,##0.00
		displayFolder: 06 Concentracao
		lineageTag: a1000001-0000-0000-0000-000000000028

	measure '% Concentracao Top 5 Fornecedores' = DIVIDE ( [Valor Top 5 Fornecedores], CALCULATE ( [Valor Total], ALL ( 'licitacoes_2019_2024'[cpfCnpjVencedor] ) ) )
		formatString: 0.0%
		displayFolder: 06 Concentracao
		lineageTag: a1000001-0000-0000-0000-000000000029

	measure 'Valor Top 10 Fornecedores' =
			VAR Top10 = TOPN ( 10, VALUES ( 'licitacoes_2019_2024'[cpfCnpjVencedor] ), [Valor Total], DESC )
			RETURN CALCULATE ( [Valor Total], Top10 )
		formatString: R$ #,##0.00
		displayFolder: 06 Concentracao
		lineageTag: a1000001-0000-0000-0000-000000000030

	measure '% Concentracao Top 10 Fornecedores' = DIVIDE ( [Valor Top 10 Fornecedores], CALCULATE ( [Valor Total], ALL ( 'licitacoes_2019_2024'[cpfCnpjVencedor] ) ) )
		formatString: 0.0%
		displayFolder: 06 Concentracao
		lineageTag: a1000001-0000-0000-0000-000000000031

	measure '% Pareto Acumulado' =
			VAR ValorAtual = [Valor Total]
			VAR TotalGeral = CALCULATE ( [Valor Total], ALL ( 'licitacoes_2019_2024'[nome] ) )
			VAR FornecedoresComMaiorOuIgualValor =
			    FILTER (
			        ALL ( 'licitacoes_2019_2024'[nome] ),
			        CALCULATE ( [Valor Total] ) >= ValorAtual
			    )
			VAR ValorAcumulado = CALCULATE ( [Valor Total], FornecedoresComMaiorOuIgualValor )
			RETURN DIVIDE ( ValorAcumulado, TotalGeral )
		formatString: 0.0%
		displayFolder: 06 Concentracao
		lineageTag: a1000001-0000-0000-0000-000000000039

	measure 'Qtd Itens Sem Categoria' = CALCULATE ( [Qtd Linhas], 'licitacoes_2019_2024'[categoria_ia] IN { "Sem Descrição", "Outros / Necessita Revisão", BLANK() } )
		formatString: #,##0
		displayFolder: 07 Qualidade de Dados
		lineageTag: a1000001-0000-0000-0000-000000000032

	measure '% Itens Bem Categorizados' = 1 - DIVIDE ( [Qtd Itens Sem Categoria], [Qtd Linhas] )
		formatString: 0.0%
		displayFolder: 07 Qualidade de Dados
		lineageTag: a1000001-0000-0000-0000-000000000033

	measure 'Confianca Media' = AVERAGE ( 'mapa_descricao'[confianca] )
		formatString: 0.000
		displayFolder: 07 Qualidade de Dados
		lineageTag: a1000001-0000-0000-0000-000000000034

	measure 'Qtd Itens Baixa Confianca' = CALCULATE ( [Qtd Linhas], FILTER ( 'mapa_descricao', 'mapa_descricao'[confianca] < 0.5 && 'mapa_descricao'[confianca] > 0 ) )
		formatString: #,##0
		displayFolder: 07 Qualidade de Dados
		lineageTag: a1000001-0000-0000-0000-000000000035

	measure '% Itens Baixa Confianca' = DIVIDE ( [Qtd Itens Baixa Confianca], [Qtd Linhas] )
		formatString: 0.0%
		displayFolder: 07 Qualidade de Dados
		lineageTag: a1000001-0000-0000-0000-000000000036

	measure 'Valor Total Formatado' =
			VAR Valor = [Valor Total]
			RETURN SWITCH ( TRUE (),
				Valor >= 1e9, FORMAT ( Valor / 1e9, "R$ #,##0.00" ) & " bi",
				Valor >= 1e6, FORMAT ( Valor / 1e6, "R$ #,##0.00" ) & " mi",
				Valor >= 1e3, FORMAT ( Valor / 1e3, "R$ #,##0.00" ) & " mil",
				FORMAT ( Valor, "R$ #,##0.00" ) )
		displayFolder: 08 Auxiliares
		lineageTag: a1000001-0000-0000-0000-000000000037

	measure 'Cor YoY' = SWITCH ( TRUE (), [Valor YoY %] > 0, "#16A34A", [Valor YoY %] < 0, "#DC2626", "#71717A" )
		displayFolder: 08 Auxiliares
		lineageTag: a1000001-0000-0000-0000-000000000038

	measure 'Forecast IC Superior' =
			IF (
			    [Valor Previsto] <> BLANK (),
			    [Valor Previsto] + 1.645 * 136657638
			)
		formatString: R$ #,##0.00
		displayFolder: 09 Forecast
		lineageTag: a1000001-0000-0000-0000-000000000041

	measure 'Forecast IC Inferior' =
			IF (
			    [Valor Previsto] <> BLANK (),
			    MAX ( 0, [Valor Previsto] - 1.645 * 136657638 )
			)
		formatString: R$ #,##0.00
		displayFolder: 09 Forecast
		lineageTag: a1000001-0000-0000-0000-000000000042

	measure 'Valor Previsto' =
			VAR vCurrentMesAnoNum = MAX ( 'Calendario'[MesAnoNumero] )
			VAR vCurrentSeqMonth = INT ( vCurrentMesAnoNum / 100 ) * 12 + MOD ( vCurrentMesAnoNum, 100 )
			VAR vLastActualDate = CALCULATE ( MAX ( 'licitacoes_2019_2024'[mes/ano] ), REMOVEFILTERS ( 'Calendario' ) )
			VAR vLastActualMesAnoNum = YEAR ( vLastActualDate ) * 100 + MONTH ( vLastActualDate )
			VAR vLastActualSeqMonth = INT ( vLastActualMesAnoNum / 100 ) * 12 + MOD ( vLastActualMesAnoNum, 100 )
			VAR vLookbackDate = EDATE ( vLastActualDate, -12 )
			VAR vLookbackMesAnoNum = YEAR ( vLookbackDate ) * 100 + MONTH ( vLookbackDate )
			VAR vTrainingTable =
			    ADDCOLUMNS (
			        CALCULATETABLE (
			            VALUES ( 'Calendario'[MesAnoNumero] ),
			            REMOVEFILTERS ( 'Calendario' ),
			            'Calendario'[MesAnoNumero] >= vLookbackMesAnoNum,
			            'Calendario'[MesAnoNumero] <= vLastActualMesAnoNum
			        ),
			        "@Y", CALCULATE ( [Valor Total], ALLEXCEPT ( 'Calendario', 'Calendario'[MesAnoNumero] ) ),
			        "@X", INT ( 'Calendario'[MesAnoNumero] / 100 ) * 12 + MOD ( 'Calendario'[MesAnoNumero], 100 )
			    )
			VAR vMeanX = AVERAGEX ( vTrainingTable, [@X] )
			VAR vMeanY = AVERAGEX ( vTrainingTable, [@Y] )
			VAR vSumXY = SUMX ( vTrainingTable, ( [@X] - vMeanX ) * ( [@Y] - vMeanY ) )
			VAR vSumX2 = SUMX ( vTrainingTable, ( [@X] - vMeanX ) ^ 2 )
			VAR vSlope = DIVIDE ( vSumXY, vSumX2 )
			VAR vIntercept = vMeanY - vSlope * vMeanX
			VAR vForecastValue = MAX ( 0, vIntercept + vSlope * vCurrentSeqMonth )
			RETURN
			IF ( vCurrentMesAnoNum >= vLastActualMesAnoNum, vForecastValue )
		formatString: R$ #,##0.00
		displayFolder: 09 Forecast
		lineageTag: a1000001-0000-0000-0000-000000000040

	column Value
		dataType: string
		isHidden
		lineageTag: c9f0e4b3-0527-4fab-8901-23456789abcd
		summarizeBy: none
		sourceColumn: [Value]

		annotation SummarizationSetBy = User

	partition _Medidas = calculated
		mode: import
		source = {BLANK()}

	annotation PBI_Id = d0a1f5c4-1638-4cbc-9012-345678901234

